### QUERY RATE DEFAULT = OFF, RUN_COMMAND = !, SET_LOCAL_VAR = $, SYSTEM_TASK_SCHEDULE = schedular.io ###
!QUERY IN > SYSTEM_TASK_SCHEDULE
$SET QUERY RATE TO 10
!QUERY IN > Image_Reaper
!QUERY IN > Text_Reaper